spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/haribjnair/cloud-config-server
    
server:
  port: 8094
  
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://192.168.1.2:8761/eureka/
 instance:
  hostname: 192.168.1.2